[2024-04-29T07:25:09.521+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T07:25:09.542+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.sensor_weather scheduled__2024-04-29T01:44:00+00:00 [queued]>
[2024-04-29T07:25:09.551+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.sensor_weather scheduled__2024-04-29T01:44:00+00:00 [queued]>
[2024-04-29T07:25:09.552+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T07:25:09.568+0000] {taskinstance.py:2327} INFO - Executing <Task(HttpSensor): sensor_weather> on 2024-04-29 01:44:00+00:00
[2024-04-29T07:25:09.578+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1016) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T07:25:09.580+0000] {standard_task_runner.py:63} INFO - Started process 1043 to run task
[2024-04-29T07:25:09.580+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'sensor_weather', 'scheduled__2024-04-29T01:44:00+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmptm5k157l']
[2024-04-29T07:25:09.581+0000] {standard_task_runner.py:91} INFO - Job 201: Subtask sensor_weather
[2024-04-29T07:25:09.637+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.sensor_weather scheduled__2024-04-29T01:44:00+00:00 [running]> on host 6dbc7f679521
[2024-04-29T07:25:09.734+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='sensor_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T01:44:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T01:44:00+00:00'
[2024-04-29T07:25:09.735+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T07:25:09.736+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-04-29T07:25:09.737+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Baku&APPID=682dec93d925536760749155cc3096bd
[2024-04-29T07:25:09.747+0000] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-04-29T07:25:10.122+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-04-29T07:25:10.123+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T07:25:10.132+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_for_open_weather, task_id=sensor_weather, execution_date=20240429T014400, start_date=20240429T072509, end_date=20240429T072510
[2024-04-29T07:25:10.276+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T07:25:10.312+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-29T07:25:10.314+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
