[2024-04-29T07:33:14.164+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T07:33:14.191+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.sensor_weather scheduled__2024-04-29T06:50:00+00:00 [queued]>
[2024-04-29T07:33:14.205+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.sensor_weather scheduled__2024-04-29T06:50:00+00:00 [queued]>
[2024-04-29T07:33:14.206+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T07:33:14.357+0000] {taskinstance.py:2327} INFO - Executing <Task(HttpSensor): sensor_weather> on 2024-04-29 06:50:00+00:00
[2024-04-29T07:33:14.367+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2685) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T07:33:14.369+0000] {standard_task_runner.py:63} INFO - Started process 2717 to run task
[2024-04-29T07:33:14.373+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'sensor_weather', 'scheduled__2024-04-29T06:50:00+00:00', '--job-id', '721', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmpbj9izyo8']
[2024-04-29T07:33:14.374+0000] {standard_task_runner.py:91} INFO - Job 721: Subtask sensor_weather
[2024-04-29T07:33:14.444+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.sensor_weather scheduled__2024-04-29T06:50:00+00:00 [running]> on host 6dbc7f679521
[2024-04-29T07:33:14.598+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='sensor_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T06:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T06:50:00+00:00'
[2024-04-29T07:33:14.602+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T07:33:14.603+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-04-29T07:33:14.604+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Baku&APPID=682dec93d925536760749155cc3096bd
[2024-04-29T07:33:14.616+0000] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-04-29T07:33:15.029+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-04-29T07:33:15.036+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T07:33:15.056+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_for_open_weather, task_id=sensor_weather, execution_date=20240429T065000, start_date=20240429T073314, end_date=20240429T073315
[2024-04-29T07:33:15.106+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T07:33:15.280+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T07:33:15.283+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
