[2024-04-29T07:25:11.878+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T07:25:11.897+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.sensor_weather scheduled__2024-04-29T02:04:00+00:00 [queued]>
[2024-04-29T07:25:11.907+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.sensor_weather scheduled__2024-04-29T02:04:00+00:00 [queued]>
[2024-04-29T07:25:11.908+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T07:25:11.924+0000] {taskinstance.py:2327} INFO - Executing <Task(HttpSensor): sensor_weather> on 2024-04-29 02:04:00+00:00
[2024-04-29T07:25:11.934+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1053) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T07:25:11.935+0000] {standard_task_runner.py:63} INFO - Started process 1076 to run task
[2024-04-29T07:25:11.943+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'sensor_weather', 'scheduled__2024-04-29T02:04:00+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmp01u9o9jn']
[2024-04-29T07:25:11.944+0000] {standard_task_runner.py:91} INFO - Job 210: Subtask sensor_weather
[2024-04-29T07:25:11.991+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.sensor_weather scheduled__2024-04-29T02:04:00+00:00 [running]> on host 6dbc7f679521
[2024-04-29T07:25:12.112+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='sensor_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T02:04:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T02:04:00+00:00'
[2024-04-29T07:25:12.116+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T07:25:12.117+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-04-29T07:25:12.118+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Baku&APPID=682dec93d925536760749155cc3096bd
[2024-04-29T07:25:12.129+0000] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-04-29T07:25:12.504+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-04-29T07:25:12.506+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T07:25:12.517+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_for_open_weather, task_id=sensor_weather, execution_date=20240429T020400, start_date=20240429T072511, end_date=20240429T072512
[2024-04-29T07:25:12.560+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T07:25:12.595+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-29T07:25:12.597+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
