[2024-04-29T07:33:16.889+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T07:33:16.906+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T06:24:00+00:00 [queued]>
[2024-04-29T07:33:16.917+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T06:24:00+00:00 [queued]>
[2024-04-29T07:33:16.918+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T07:33:16.932+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-04-29 06:24:00+00:00
[2024-04-29T07:33:16.942+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2731) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T07:33:16.944+0000] {standard_task_runner.py:63} INFO - Started process 2759 to run task
[2024-04-29T07:33:16.944+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'transform_load_weather_data', 'scheduled__2024-04-29T06:24:00+00:00', '--job-id', '738', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmpdh5xmo5t']
[2024-04-29T07:33:16.945+0000] {standard_task_runner.py:91} INFO - Job 738: Subtask transform_load_weather_data
[2024-04-29T07:33:17.009+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T06:24:00+00:00 [running]> on host 6dbc7f679521
[2024-04-29T07:33:17.122+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T06:24:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T06:24:00+00:00'
[2024-04-29T07:33:17.124+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T07:33:17.150+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-29T07:33:17.150+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T07:33:17.158+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_for_open_weather, task_id=transform_load_weather_data, execution_date=20240429T062400, start_date=20240429T073316, end_date=20240429T073317
[2024-04-29T07:33:17.205+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T07:33:17.320+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T07:33:17.333+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
