[2024-04-29T09:26:28.792+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T09:26:28.812+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.open_weather_sensor scheduled__2024-04-29T08:50:00+00:00 [queued]>
[2024-04-29T09:26:28.824+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.open_weather_sensor scheduled__2024-04-29T08:50:00+00:00 [queued]>
[2024-04-29T09:26:28.825+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T09:26:28.843+0000] {taskinstance.py:2327} INFO - Executing <Task(HttpSensor): open_weather_sensor> on 2024-04-29 08:50:00+00:00
[2024-04-29T09:26:28.852+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3039) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T09:26:28.853+0000] {standard_task_runner.py:63} INFO - Started process 3065 to run task
[2024-04-29T09:26:28.853+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'open_weather_sensor', 'scheduled__2024-04-29T08:50:00+00:00', '--job-id', '844', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmpg1idezeq']
[2024-04-29T09:26:28.854+0000] {standard_task_runner.py:91} INFO - Job 844: Subtask open_weather_sensor
[2024-04-29T09:26:28.894+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.open_weather_sensor scheduled__2024-04-29T08:50:00+00:00 [running]> on host ce94facc171a
[2024-04-29T09:26:28.978+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='open_weather_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T08:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T08:50:00+00:00'
[2024-04-29T09:26:28.979+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T09:26:28.980+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-04-29T09:26:28.980+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Baku&APPID=682dec93d925536760749155cc3096bd
[2024-04-29T09:26:28.990+0000] {base.py:84} INFO - Using connection ID 'weather_id' for task execution.
[2024-04-29T09:26:29.369+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-04-29T09:26:29.371+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T09:26:29.383+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_for_open_weather, task_id=open_weather_sensor, execution_date=20240429T085000, start_date=20240429T092628, end_date=20240429T092629
[2024-04-29T09:26:29.430+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T09:26:29.475+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-29T09:26:29.477+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
