[2024-04-29T07:25:12.165+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T07:25:12.193+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.sensor_weather scheduled__2024-04-29T02:00:00+00:00 [queued]>
[2024-04-29T07:25:12.205+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.sensor_weather scheduled__2024-04-29T02:00:00+00:00 [queued]>
[2024-04-29T07:25:12.206+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T07:25:12.224+0000] {taskinstance.py:2327} INFO - Executing <Task(HttpSensor): sensor_weather> on 2024-04-29 02:00:00+00:00
[2024-04-29T07:25:12.233+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1044) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T07:25:12.235+0000] {standard_task_runner.py:63} INFO - Started process 1082 to run task
[2024-04-29T07:25:12.235+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'sensor_weather', 'scheduled__2024-04-29T02:00:00+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmpnleo09wc']
[2024-04-29T07:25:12.237+0000] {standard_task_runner.py:91} INFO - Job 213: Subtask sensor_weather
[2024-04-29T07:25:12.286+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.sensor_weather scheduled__2024-04-29T02:00:00+00:00 [running]> on host 6dbc7f679521
[2024-04-29T07:25:12.371+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='sensor_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T02:00:00+00:00'
[2024-04-29T07:25:12.373+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T07:25:12.373+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-04-29T07:25:12.374+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Baku&APPID=682dec93d925536760749155cc3096bd
[2024-04-29T07:25:12.383+0000] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-04-29T07:25:12.782+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-04-29T07:25:12.784+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T07:25:12.793+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_for_open_weather, task_id=sensor_weather, execution_date=20240429T020000, start_date=20240429T072512, end_date=20240429T072512
[2024-04-29T07:25:12.813+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T07:25:12.835+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-29T07:25:12.837+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
